---
# Playbook for conditions

- name: Playbook to implement conditions concepts
  hosts: all
  user: ansible
  become: yes
  connection: ssh

  tasks:
   - name: Install apache on debian
     command: apt-get -y install apache2
     when: ansible_os_family== "Debian"

   - name: Install httpd on redhat
     command: yum install httpd -y
     when: ansible_os_family== "RedHat"
